version: '3.8' # Defines the Docker Compose version we're using

# Defines the services that make up the app
services:
  # The PHP container
  appserver:
    # command: sh -c "a2enmod rewrite && apache2-foreground"
    # Using the Lando PHP image ensures compatibility
    build: .
    # image: devwithlando/php:8.1-apache-4
    command: bash -c "a2enmod rewrite && apache2-foreground"
    # Maps the ports between the host and the container
    ports:
      # Maps host port 80 to container's Apache HTTP port
      - "8082:80"
      # Maps host port 443 to container's Apache HTTPS port
      - "8445:443"
    # Mounts directories between the host and the container
    volumes:
      # Bind mount for Drupal files
      - type: bind
        source: ./html/sites/default/files
        target: /var/www/html/sites/default/files
        bind:
          propagation: shared
      user: "${HTTP_UID}:${HTTP_GID}"
    # Environment variables to set inside the container
    environment:
      - USER_ID=${HTTP_UID}
      - GROUP_ID=${HTTP_GID}
  # The MySQL container
  database:
    # Using the Lando MySQL image for compatibility
    image: bitnami/mysql:5.7.29-debian-10-r51
    volumes:
      # Mounts a volume for data persistence
      - mysql_data_drupal_blog:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes: # Volume definition for data persistence
  mysql_data_drupal_blog: # Named volume to persist MySQL data between container restarts or rebuilds

