<?php

declare(strict_types=1);

/**
 * @file
 * Provides a listable book entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function book_forge_theme(): array {
  return [
    'book_forge_book' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for listable book templates.
 *
 * Default template: book-forge-book.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the listable book information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_book_forge_book(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function book_forge_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish listable books.
      $storage = \Drupal::entityTypeManager()->getStorage('book_forge_book');
      $book_forge_book_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($book_forge_book_ids) as $book_forge_book) {
        $book_forge_book->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize listable books.
      $storage = \Drupal::entityTypeManager()->getStorage('book_forge_book');
      $book_forge_book_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($book_forge_book_ids) as $book_forge_book) {
        $book_forge_book->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function book_forge_user_predelete(UserInterface $account): void {
  // Delete listable books that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('book_forge_book');
  $book_forge_book_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($book_forge_book_ids)
  );
}
