#!/bin/bash

set -e

# Default HOMEPAGE value if not provided
HOMEPAGE=${HOMEPAGE:-video-react}

REACT_DIR=/var/www/html/video-react
TARGET_DIR="/var/www/html/html/${HOMEPAGE}"

mkdir -p "$TARGET_DIR"

echo "🌐 Setting homepage to: /${HOMEPAGE}/"
cd "$REACT_DIR"
#npm set homepage "/${HOMEPAGE}/" # only for npm v9+
jq ".homepage = \"/${HOMEPAGE}/\"" package.json > package.tmp.json && mv package.tmp.json package.json

echo "🚀 Building React app in: $REACT_DIR"
npm run build

echo "🧹 Removing old build at: $TARGET_DIR"
rm -rf "$TARGET_DIR"/*

echo "📂 Copying new build to Drupal webroot: $TARGET_DIR"
cp -r "$REACT_DIR/build/"* "$TARGET_DIR/"

echo "✅ React app deployed to /${HOMEPAGE}/"

